
services:
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:latest
    container_name: adminer_ui
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
  
  backend-django:
    build: 
      context: ./backend-django
      dockerfile: Dockerfile.prod
    container_name: django-docker
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./backend-django:/app 
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/kanban_django
    env_file:
      - ./backend-django/.env
    depends_on:
      db:
        condition: service_healthy
  
  backend-fastapi:
    build: 
      context: ./backend-fastapi
      dockerfile: Dockerfile.prod
    container_name: fastapi-docker
    restart: unless-stopped
    ports:
      - "8001:8000"
    volumes:
      - ./backend-fastapi:/app
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/kanban_fastapi
    env_file:
      - ./backend-fastapi/.env
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
